---
abstract: 'The great new DBD::SQLite::FTS3Transitional!'
author:
  - 'Laurent Dami <dami@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBD-SQLite-FTS3Transitional
provides:
  DBD::SQLite::FTS3Transitional:
    file: lib/DBD/SQLite/FTS3Transitional.pm
    version: 1.00
resources:
  license: http://dev.perl.org/licenses/
version: 1.00
